trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
      - script: echo Building project . . .
        displayName: 'Build Project'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/consoleasync.csproj'


  - job: Deploy
    dependsOn: Build
    condition: succeeded()
    steps:
      - script: echo Deploying project . . .
        displayName: 'Deploy Project'
      - task: AzureStaticWebApp@0
        inputs:
          app_location: 'ResumeWebsite/wwwroot/'
          azure_static_web_apps_api_token: $(token)
          production_branch: 'main'
          
      - checkout: self
        submodules: true
      - task: AzureStaticWebApp@0
        inputs:
          app_location: '/'
          api_location: 'api'
          output_location: 'wwwroot'
        env:
          azure_static_web_apps_api_token: $(token)
