   trigger:
     - main

   pool:
     vmImage: 'ubuntu-latest'

   steps:
   - script: dotnet build --configuration Release
     displayName: 'Build project'

   - task: PublishBuildArtifacts@1
     inputs:
       PathtoPublish: 'bin/Release/netcoreapp3.1/publish'
       ArtifactName: 'drop'
       publishLocation: 'Container'