trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
    - script: ls -la $(Build.SourcesDirectory)
      displayName: 'List directories at the source root'
    
    - script: dotnet build --configuration Release
      displayName: 'Build project'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'bin/Release/netcoreapp3.1/publish'
        ArtifactName: 'drop'
        publishLocation: 'Container'

  - job: Deploy
    dependsOn: Build
    condition: succeeded()
    steps:
    - script: echo Deploy your project here
      displayName: 'Deploy Project'